services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Task_CRUD
    ports:
      - "5432:5432"
    volumes:
      - ./store/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Task_CRUD"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_crud
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure